# 默认RVC X Mini 3D相机参数
# 相机类型：彩色相机
type: "rgb"
# 曝光时间 (3~100) ms
exposure_time_2d: 100
exposure_time_3d: 20
# 增益
gain_2d: 4.0
gain_3d: 0.0
# Gamma
gamma_2d: 0.312
gamma_3d: 1.0
# 边缘去噪阈值, 取值范围 [0, 10]
edge_noise_reduction_threshold: 0
# 投影颜色
# 建议选择白色光投影
# 可选颜色: ["red", "green", "blue", "white"]
projector_color: "blue"
# 光强对比度阈值
light_contrast_threshold: 2
