# 默认RVC X Mini 3D相机参数

# 曝光时间 (3~100) ms
exposure_time_2d: 100
exposure_time_3d: 20
# 增益
gain_2d: 18.0
gain_3d: 0.0
# Gamma
gamma_2d: 0.566
gamma_3d: 1
# 边缘去噪阈值, 取值范围 [0, 10]
edge_noise_reduction_threshold: 2
# 投影颜色
# 可选颜色: ["red", "green", "blue"]
projector_color: "green"
# 光强对比度阈值
light_contrast_threshold: 3