# 拍摄小鸭子的相机参数
# 相机类型：彩色相机
type: "rgb"
# 曝光时间 (3~100) ms
exposure_time_2d: 100
exposure_time_3d: 100
# 增益
gain_2d: 18.026
gain_3d: 0.365
# Gamma
gamma_2d: 0.566
gamma_3d: 1
# 边缘去噪阈值, 取值范围 [0, 10]
edge_noise_reduction_threshold: 3
# 投影颜色
# 可选颜色: ["red", "green", "blue"]
projector_color: "green"
# 光强对比度阈值
light_contrast_threshold: 3